
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

new_http_archive(
    name = "spdlog",
    urls = ["https://github.com/gabime/spdlog/archive/v1.x.zip"],
    strip_prefix = "spdlog-1.x",
    build_file = "BUILD.spdlog",
)

new_http_archive(
    name = "json",
    urls = ["https://github.com/nlohmann/json/archive/develop.zip"],
    #strip_prefix = "spdlog-1.x",
    build_file = "BUILD.json",
)
